---
- hosts: fw
  gather_facts: false
  connection: local

  vars_files:
    - vars/fw_vars.yml

  roles:
    - PaloAltoNetworks.paloaltonetworks

  tasks:
    - name: Check to see if firewall is ready
      panos_check:
        provider: '{{ firewall }}'
        timeout: 30