---
- hosts: firewall
  gather_facts: false
  connection: local

  roles:
    - PaloAltoNetworks.paloaltonetworks

  tasks:
    - name: Check to see if firewall is ready
      panos_check:
        provider: '{{ provider }}'
        timeout: 30