---
- hosts: fw
  gather_facts: false
  connection: local

  vars_files:
    - vars/fw_vars.yml

  module_defaults:
    panos_security_rule:
      ip_address: '{{ fw_ip_address }}'
      username: '{{ fw_username }}'
      password: '{{ fw_password }}'
      state: 'present'
      commit: false
    panos_nat_rule:
      ip_address: '{{ fw_ip_address }}'
      username: '{{ fw_username }}'
      password: '{{ fw_password }}'
      commit: false

  tasks:
    - name: Create security rules
      panos_security_rule:
        rule_name: '{{ item.name }}'
        source_zone: ['untrust']
        destination_zone: ['trust']
        source_ip: ['any']
        destination_ip: '{{ item.destination }}'
        application: '{{ item.application }}'
        service: ['application-default']
        action: 'allow'
        tag_name: '{{ item.tag }}'
      with_items:
        - { name: 'Prod SSH Inbound', destination: ['Prod-Instances'], application: ['ssh'], tag: ['Prod'] }
        - { name: 'SI Inbound', destination: ['SI-Instances'], application: ['ssh', 'mysql'], tag: ['SI'] }