---
- hosts: firewall
  connection: local
  gather_facts: false

  roles:
    - PaloAltoNetworks.paloaltonetworks

  tasks:
    - name: Issue firewall shutdown command
      panos_op:
        provider: '{{ provider }}'
        cmd: '<request><shutdown><system></system></shutdown></request>'
        cmd_is_xml: True
